sonar.tests=.
sonar.test.inclusions=**/*Test.java,**/*TI.java
sonar.sources=trace-publisher/src/main/java,trace-consumer/src/main/java,trace-contract/src/main/java
sonar.java.binaries=trace-publisher/target/classes,trace-consumer/target/classes,trace-contract/target/classes
sonar.coverage.jacoco.xmlReportPaths=trace-publisher/target/site/jacoco/jacoco.xml,trace-consumer/target/site/jacoco/jacoco.xml,trace-contract/target/site/jacoco/jacoco.xml

# Ignore S100 (method naming) only for test classes
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*Test.java,**/*TI.java