# ===============================
# Spring Core / Server
# ===============================
server.port=9080
server.timezone=Europe/Paris
spring.main.banner-mode=off
spring.main.log-startup-info=true

# ===============================
# Datasource POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5429/trace_rabbit_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD:123456789}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=false

# ===============================
# RABBIT_MQ
# ===============================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD:admin}
spring.rabbitmq.virtual-host=/traces

# ===============================
# TRACE MANAGEMENT
# ===============================
trace.rabbit.exchange=trace.topic
trace.rabbit.routing-key-template=trace.%s

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health, info, startup, flyway, metrics
management.metrics.export.prometheus.enabled=true
management.endpoint.flyway.enabled=true
management.endpoint.startup.enabled=true
management.server.port=9086

# ===============================
# OpenAPI
# ===============================
springdoc.show-actuator=true
springdoc.use-management-port=false

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls[0].name=admin
springdoc.swagger-ui.urls[0].url=/v3/api-docs/admin
springdoc.swagger-ui.urls[1].name=actuator
springdoc.swagger-ui.urls[1].url=/v3/api-docs/actuator

springdoc.group-configs[0].group=admin
springdoc.group-configs[0].paths-to-match=/admin/**
springdoc.group-configs[1].group=actuator
springdoc.group-configs[1].paths-to-match=/actuator/**

# ===============================
# Logging
# ===============================

logging.level.org.flywaydb=DEBUG
logging.level.org.hibernate.orm.connections.pooling=WARN

logging.level.org.springframework.boot.context.config=DEBUG

logging.level.fr.cnamts.cpam33.traces.publisher.services=TRACE
logging.level.fr.cnamts.cpam33.traces.publisher.api=TRACE