spring.datasource.url=jdbc:postgresql://localhost:5423/dlq_admin
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD:123456789}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=${RABBIT_MQ_PASSWORD:admin}
spring.rabbitmq.listener.simple.acknowledge-mode=manual

dlq-admin.dlq-queue=trace.queue.dlq
dlq-admin.republish.default-exchange=""
dlq-admin.republish.default-routing-key=trace.queue.0
dlq-admin.republish.prefer-original-from-x-death=true
dlq-admin.security.api-key="changeme"
